name: py311
channels:
  - defaults
  - conda-forge
dependencies:
  - geopandas>=1.1.1
  - pandas>=0.23.0
  - polars>=1.33.1
  - requests>=2.32.5
  - jupyterlab>=4.4.7
  - folium>=0.20.0
  - python=3.11
